import os
import time
import logging
from pathlib import Path
from datetime import datetime, timedelta

# Root path setup
script_dir = Path(__file__).resolve().parent.parent
vault_path = script_dir / "AI_Employee" / "vault"

def get_financial_metrics():
    """
    Mocking data retrieval from Odoo/Accounting folder.
    """
    # Logic: Search /Accounting/ for latest month's CSV or JSON
    # For now, we simulate values
    return {
        "revenue": 12500,
        "expenses": 4200,
        "profit": 8300,
        "unpaid_invoices": 2,
        "subscription_costs": 450
    }

def get_task_metrics():
    """
    Calculates completion rate and delays from /Done and /Plans.
    """
    done_dir = vault_path / "Done"
    plans_dir = vault_path / "Plans"
    
    done_count = len(list(done_dir.glob("*.md")))
    plan_count = len(list(plans_dir.glob("*.md")))
    
    total = done_count + plan_count
    rate = (done_count / total * 100) if total > 0 else 0
    
    # Mocking delays based on file age or markers
    delays = 3 # Simulated: 3 tasks past due date
    response_time = "1.5 hours" # Simulated avg from logs
    
    return {
        "done": done_count,
        "pending": plan_count,
        "completion_rate": f"{rate:.1f}%",
        "delays": delays,
        "avg_response": response_time
    }

def get_suggestions(fin, tasks):
    suggestions = []
    if fin["unpaid_invoices"] > 0:
        suggestions.append("Follow up on unpaid invoices to boost cash flow.")
    if fin["expenses"] > 5000:
        suggestions.append("Review operational expenses. Consider canceling unused subscriptions ($450/mo).")
    if tasks["delays"] > 0:
        suggestions.append(f"Clear the {tasks['delays']} delayed tasks to maintain operational velocity.")
    
    if not suggestions:
        suggestions.append("Continue current growth strategy. Everything is on track.")
    
    return suggestions

def generate_briefing():
    today = datetime.now().strftime("%Y-%m-%d")
    briefing_file = vault_path / "Briefings" / f"{today}_CEO_Briefing.md"
    
    fin = get_financial_metrics()
    tasks = get_task_metrics()
    sug = get_suggestions(fin, tasks)
    
    content = f"""# Monday Morning CEO Briefing: {today}

## Executive Summary
Operational health is **Stable**. The system has successfully processed **{tasks['done']} tasks** this week with a completion rate of **{tasks['completion_rate']}**. Revenue is currently at **${fin['revenue']}**.

## Revenue
- **Total Revenue:** ${fin['revenue']}
- **Unpaid Invoices:** {fin['unpaid_invoices']}
- **Receivables Status:** Follow-up required.

## Expenses
- **Total Expenses:** ${fin['expenses']}
- **Subscription Costs:** ${fin['subscription_costs']}
- **Profit:** ${fin['profit']}

## Completed Tasks
- **Tasks Finished:** {tasks['done']}
- **Completion Rate:** {tasks['completion_rate']}
- **Average Response Time:** {tasks['avg_response']}

## Bottlenecks
- **Project Delays:** {tasks['delays']} tasks are currently past their scheduled completion.
- **Client Follow-ups:** 2 pending responses in Inbox.

## Suggestions
{chr(10).join([f"- {s}" for s in sug])}

---
*Generated by Autonomous FTE CEO Briefing System*
"""
    briefing_file.write_text(content, encoding='utf-8')
    print(f"CEO Briefing generated: {briefing_file.name}")

if __name__ == "__main__":
    generate_briefing()
