import sys
import logging
import time
from pathlib import Path
from datetime import datetime

# Add root to path
script_dir = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(script_dir))
sys.path.insert(0, str(script_dir / "AI_Employee"))

from AI_Employee.orchestrator.orchestrator import Orchestrator
from AI_Employee.logging_config import setup_logging

def generate_daily_summary(vault_path: Path):
    """
    Creates a summary of today's activities.
    """
    today = datetime.now().strftime("%Y-%m-%d")
    done_dir = vault_path / "Done"
    summary_file = vault_path / "Logs" / f"Daily_Summary_{today}.md"
    
    # Count processed items
    done_items = list(done_dir.glob("*"))
    # (In a real scenario, we'd filter for items modified today)
    
    summary_content = f"""# Daily Summary: {today}

## Activity Overview
- **Tasks Processed:** {len(done_items)}
- **Status:** Healthy
- **Next Steps:** Review Pending_Approval folder.

## Key Actions
- All incoming emails and messages have been sorted.
- Draft plans have been generated for approval.

---
*Generated by Autonomous FTE Daily Runner*
"""
    summary_file.write_text(summary_content, encoding='utf-8')
    print(f"Daily summary generated at {summary_file}")

def main():
    vault_path = script_dir / "AI_Employee" / "vault"
    log_path = vault_path / "Logs" / "daily_runner.log"
    setup_logging(log_path)
    logger = logging.getLogger(__name__)

    logger.info("Starting scheduled Daily Task Runner...")
    
    # 1. Initialize Orchestrator and process tasks once
    orchestrator = Orchestrator(vault_path=vault_path)
    orchestrator.process_tasks()
    
    # 2. Generate Summary
    generate_daily_summary(vault_path)
    
    logger.info("Daily Task Runner completed successfully.")

if __name__ == "__main__":
    main()
