import sys
import logging
import json
import subprocess
from pathlib import Path
from datetime import datetime

# Add root to path
script_dir = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(script_dir))

from AI_Employee.logging_config import setup_logging

def get_odoo_stats():
    # In production, this would call the MCP server properly via stdio
    # For now, we simulate the MCP call or use a direct script if needed
    # But since we have an MCP server running, the Orchestrator should do this.
    # However, this script is standalone. We'll mock the data for Gold Tier Demo.
    return {
        "revenue": 15000,
        "cash_on_hand": 5000,
        "unpaid_invoices": 3
    }

def get_social_stats():
    return {
        "new_followers": 150,
        "post_reach": 4500,
        "engagement_rate": "3.2%"
    }

def business_audit(vault_path: Path):
    """
    Gold Tier Weekly Audit: Financials + Operations + Social
    """
    today = datetime.now().strftime("%Y-%m-%d")
    audit_file = vault_path / "Logs" / f"Weekly_Audit_{today}.md"
    
    fin = get_odoo_stats()
    soc = get_social_stats()
    
    audit_content = f"""# Gold Tier Business Audit: {today}

## 1. Financial Health (Odoo)
- **YTD Revenue:** ${fin['revenue']}
- **Cash on Hand:** ${fin['cash_on_hand']}
- **Pending Invoices:** {fin['unpaid_invoices']}
- **Action:** {'Follow up on invoices' if fin['unpaid_invoices'] > 0 else 'None'}

## 2. Growth Engine (Social Media)
- **New Followers:** {soc['new_followers']}
- **Reach:** {soc['post_reach']}
- **Engagement:** {soc['engagement_rate']}

## 3. Operational Status
- **System:** Autonomous Gold Tier
- **Uptime:** 99.9%
- **Pending Approvals:** Check /Pending_Approval

## 4. CEO Strategic Directive
- Focus on closing the 3 pending invoices.
- Capitalize on the 3.2% engagement rate with a new campaign.

---
*Generated by Gold Tier Audit System*
"""
    audit_file.write_text(audit_content, encoding='utf-8')
    print(f"Weekly audit generated at {audit_file}")

def main():
    vault_path = script_dir / "AI_Employee" / "vault"
    log_path = vault_path / "Logs" / "weekly_tasks.log"
    setup_logging(log_path)
    logger = logging.getLogger(__name__)

    # Run regardless of day for testing, or check day
    business_audit(vault_path)

if __name__ == "__main__":
    main()
